# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - manasgpt

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://bigagi.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_5dc036411bb3497c9a2c553c974f8db5 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_9705bbdd9dc5463f933fbbfaf7779e8c }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: bigagi.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_5dc036411bb3497c9a2c553c974f8db5 }}/chatmanas.azurecr.io/webimage:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'manasgpt'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_a23ba022ee0245e4890fa3d31aebbaec }}
        images: 'bigagi.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_5dc036411bb3497c9a2c553c974f8db5 }}/chatmanas.azurecr.io/webimage:${{ github.sha }}'