# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - manasgpt

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://bigagi.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_e4e47c86068046918afee6542317cc87 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_c1eb737288a3443b90bdec0aa92290ce }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: bigagi.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_e4e47c86068046918afee6542317cc87 }}/bigagi:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'manasgpt'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_bc7f344462f44f7eb85a171294eb9988 }}
        images: 'bigagi.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_e4e47c86068046918afee6542317cc87 }}/bigagi:${{ github.sha }}'